name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt

    - name: Set up pre-commit cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run pre-commit
      run: |
        pre-commit install
        pre-commit run --all-files
      env:
        SKIP: pytest,pytest-check  # Skip test hooks to avoid needing runtime dependencies

    - name: Run bandit
      run: |
        # Create a simple bandit config if it doesn't exist
        if [ ! -f .bandit.yaml ]; then
          echo "---\nexclude_dirs:\n  - tests\nskips:\n  - B101\n  - B104\n  - B105\n  - B110\n  - B303\n  - B311\n  - B314\n  - B320\n  - B404\n  - B603\n  - B607\nconfidence: MEDIUM" > .bandit.yaml
        fi
        bandit -r . -c .bandit.yaml --exclude tests/,venv/,.venv/,env/,.env/

    - name: Run flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
